//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lemonwayToolboxClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.lemonwayToolBoxSoap")]
    public interface lemonwayToolBoxSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FibonacciValue", ReplyAction="*")]
        double FibonacciValue(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FibonacciValue", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FibonacciValueAsync(int value);
        
        // CODEGEN: Generating message contract since element name Xmlvalue from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJsonParser", ReplyAction="*")]
        lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponse XmlToJsonParser(lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJsonParser", ReplyAction="*")]
        System.Threading.Tasks.Task<lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponse> XmlToJsonParserAsync(lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonParserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonParser", Namespace="http://tempuri.org/", Order=0)]
        public lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequestBody Body;
        
        public XmlToJsonParserRequest() {
        }
        
        public XmlToJsonParserRequest(lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonParserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Xmlvalue;
        
        public XmlToJsonParserRequestBody() {
        }
        
        public XmlToJsonParserRequestBody(string Xmlvalue) {
            this.Xmlvalue = Xmlvalue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonParserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonParserResponse", Namespace="http://tempuri.org/", Order=0)]
        public lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponseBody Body;
        
        public XmlToJsonParserResponse() {
        }
        
        public XmlToJsonParserResponse(lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonParserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonParserResult;
        
        public XmlToJsonParserResponseBody() {
        }
        
        public XmlToJsonParserResponseBody(string XmlToJsonParserResult) {
            this.XmlToJsonParserResult = XmlToJsonParserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface lemonwayToolBoxSoapChannel : lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class lemonwayToolBoxSoapClient : System.ServiceModel.ClientBase<lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap>, lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap {
        
        public lemonwayToolBoxSoapClient() {
        }
        
        public lemonwayToolBoxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public lemonwayToolBoxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lemonwayToolBoxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lemonwayToolBoxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FibonacciValue(int value) {
            return base.Channel.FibonacciValue(value);
        }
        
        public System.Threading.Tasks.Task<double> FibonacciValueAsync(int value) {
            return base.Channel.FibonacciValueAsync(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponse lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap.XmlToJsonParser(lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest request) {
            return base.Channel.XmlToJsonParser(request);
        }
        
        public string XmlToJsonParser(string Xmlvalue) {
            lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest inValue = new lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest();
            inValue.Body = new lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequestBody();
            inValue.Body.Xmlvalue = Xmlvalue;
            lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponse retVal = ((lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap)(this)).XmlToJsonParser(inValue);
            return retVal.Body.XmlToJsonParserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponse> lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap.XmlToJsonParserAsync(lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest request) {
            return base.Channel.XmlToJsonParserAsync(request);
        }
        
        public System.Threading.Tasks.Task<lemonwayToolboxClient.ServiceReference1.XmlToJsonParserResponse> XmlToJsonParserAsync(string Xmlvalue) {
            lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest inValue = new lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequest();
            inValue.Body = new lemonwayToolboxClient.ServiceReference1.XmlToJsonParserRequestBody();
            inValue.Body.Xmlvalue = Xmlvalue;
            return ((lemonwayToolboxClient.ServiceReference1.lemonwayToolBoxSoap)(this)).XmlToJsonParserAsync(inValue);
        }
    }
}
